defmodule Zombi.Repo.Migrations.AddPlayerOnline do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:players) do
      add :online, :boolean, null: false, default: false
    end
  end

  def down do
    alter table(:players) do
      remove :online
    end
  end
end