defmodule Zombi.Repo.Migrations.AddStatsResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:server_events, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :note, :text
      add :username, :text
      add :kind, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:players, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :last_seen_at, :utc_datetime_usec
      add :health, :float
      add :zombie_kills, :bigint
      add :hours_survived, :float
      add :username, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:players, [:username], name: "players_unique_username_index")

    create table(:player_snapshots, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :hours_survived, :float
      add :zombie_kills, :bigint
      add :username, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:player_snapshots)

    drop_if_exists unique_index(:players, [:username], name: "players_unique_username_index")

    drop table(:players)

    drop table(:server_events)
  end
end